spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET time_zone = '+09:00'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: Asia/Seoul

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

swagger:
  local-server-url: ${SWAGGER_LOCAL_SERVER_URL:http://localhost:8080}
  deploy-server-url: ${SWAGGER_DEPLOY_SERVER_URL:http://54.184.58.176}

file:
  upload:
    bucket-name: ${S3_BUCKET_NAME:project5-42-oregon-feetfit-s3}
    region: ${AWS_REGION:us-west-2}
    public-url-prefix: ${S3_PUBLIC_URL_PREFIX:https://project5-42-oregon-feetfit-s3.s3.us-west-2.amazonaws.com}
    aws-cli-path: /usr/bin/aws

hardware:
  measurement:
    start-url: ${HARDWARE_MEASUREMENT_START_URL:https://bf29-2001-e60-3162-4147-da3a-ddff-fe82-9fa6.ngrok-free.app/api/reports/all}
