spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

swagger:
  local-server-url: ${SWAGGER_LOCAL_SERVER_URL:http://localhost:8080}
  deploy-server-url: ${SWAGGER_DEPLOY_SERVER_URL:http://54.184.58.176}

file:
  upload:
    bucket-name: ${S3_BUCKET_NAME:project5-42-oregon-feetfit-s3}
    region: ${AWS_REGION:us-west-2}
    public-url-prefix: ${S3_PUBLIC_URL_PREFIX:https://project5-42-oregon-feetfit-s3.s3.us-west-2.amazonaws.com}
